name: A.B.M Tafsirul Islam
tagline: Electrical and Electronic Engineer
career-objective: Dynamic and results-driven Electrical and Electronics Engineer with a strong passion for innovation and a solid academic foundation. Seeking a challenging and rewarding role where I can leverage my technical expertise and problem-solving skills to design, develop, and optimize cutting-edge electrical and electronic systems. Dedicated to staying at the forefront of emerging technologies, I aim to contribute to projects that have a positive impact on society while continuously expanding my knowledge and expertise in a collaborative and growth-oriented environment.
avatar-filename: avatar.png # Change to your avatar's filename
url: academicportfolio.github.io
baseurl: /
paginate: 5
paginate_path: "/blog/page:num/"

# Social Information
social:
  email: 
    visibility: true
    mail: abmtafsirulislam@gmail.com
  github: 
    visibility: true
    handle: abmtafsir
  linkedin: 
    visibility: true
    handle: A.B.M. Tafsirul Islam

# Collections
collections:
  experience:
    output: false
    sort_by: order
  education:
    output: false
    sort_by: order
  projects:
    output: true
    sort_by: year
  skills:
    output: false
    sort_by: order
  publications:
    output: true
    sort_by: year
  volunteerexperience:
    output: false
    sort_by: order
  certifications:
    output: false
    sort_by: year
  achievements:
    output: false
    sort_by: year

# About Page Options
collection_option:
  experience: 
    label: Experience
    visibility: true
  education: 
    label: Education
    visibility: true
  projects: 
    label: Projects
    visibility: true
  skills: 
    label: Technical Skills
    visibility: true
  publications: 
    label: Publications
    visibility: true
  volunteerexperience: 
    label: Volunteer Experience
    visibility: true
  certifications: 
    label: Certifications
    visibility: true
  achievements: 
    label: Achievements
    visibility: true

navigation:
- title: About
  url: /
- title: Blog
  url: /blog/
- title: Contact
  url: /contact

include:
  - _pages

exclude:
  - readme.md

# Defaults
defaults:
  - scope:
      path: ''
      type: posts
    values:
      permalink: /:categories/:year/:month/:title
      layout: post
      comments: true
  - scope:
      path: ''
      type: projects
    values:
      permalink: /projects/:title
      layout: project
      comments: false
  - scope:
      path: ''
      type: publications
    values:
      permalink: /publications/:title
      layout: publication
      comments: false

# Disqus Comment
disqus:
  shortname: academic-portfolio # Change with your own disqus shortname

# Contact Form
formspree:
  endpoint: https://formspree.io/f/xdorkgkv # Change with your own form's endpoint

# Google Analytics
google_analytics: UA—XXXXXXXX-X
